#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Transform urls into temporary files

Usage: unurl [-h] [-n name] [URL]

Argument:
    URL     URL to download

Options:
    -h, --help          Print this help and exit.
    -n, --name name     Use `name' as the temporary file name.
"""

import re
import os
import sys
from docopt import docopt


def file_extension(url, *, extreg=re.compile("[^/]/[^/?]+(\.[^/?.]+)(\?|$)")):
    result = extreg.findall(url)
    if not result:
        return ""
    return result[0][0]


def create_secure_directory(dirname):
    try:
        previous_umask = os.umask(0o077)
        os.mkdir(dirname)
        os.umask(previous_umask)
    except FileExistsError:
        pass

    os.chdir(dirname)

    dir_stat = os.stat(".")

    if (dir_stat.st_uid != os.getuid() or dir_stat.st_mode & 0o777 != 0o700):
        print("Wrong directory permissions", file=sys.stderr)
        exit(1)


def main():
    args    = docopt(__doc__)
    url     = args["URL"]
    name    = args["--name"] or "tmp_unurl"
    tmp_dir = "/tmp/unurl-%s" % os.getuid()

    create_secure_directory(tmp_dir)

    if not url:
        print(tmp_dir + "/" + name)
        return

    if '://' not in url:
        print(url)
        return

    import requests
    r = requests.get(url)
    with open(name, "wb") as f:
        f.write(r.content)

    ext = file_extension(url)
    if ext:
        try:
            os.remove(name + ext)
        except FileNotFoundError:
            pass
        os.symlink(name, name + ext)
        name = name + ext

    print(tmp_dir + "/" + name)

if __name__ == "__main__":
    main()
